---
name: DNSControl CLI Action
description: Check, preview and deploy your DNS configuration to multiple providers
author: William Gérald Blondel <contact@williamblondel.fr>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
  config_file:
    description: Path to DNSControl configuration file.
    required: false
    default: 'dnsconfig.js'
  creds_file:
    description: Path to DNSControl credentials file.
    required: false
    default: 'creds.json'
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
