---
name: DNSControl Action with fetch
description: Deploy your DNS configuration to multiple providers
author: Jniklas2 <github@sl.crcr.tech>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
  config_file:
    description: Path to DNSControl configuration file.
    required: false
    default: 'dnsconfig.js'
  creds_file:
    description: Path to DNSControl credentials file.
    required: false
    default: 'creds.json'
  allow_fetch:
    description: Enable the fetch function.
    required: false
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
